# Generated by Django 6.1.1 on 2026-09-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_alter_contact_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('admission_number', models.CharField(max_length=30, unique=True)),
                ('email_adress', models.EmailField(max_length=254)),
                ('p_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=128)),
                ('confirm_password', models.CharField(max_length=128)),
            ],
        ),
    ]
