# Generated by Django 6.1.1 on 2026-09-04 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_studen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studen',
            new_name='Student',
        ),
    ]
