# Generated by Django 6.1.1 on 2026-09-04 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_rename_studen_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
